version: "3"

services:
  backend:
    image: backend:latest
    build: ./Backend
    container_name: backend-latest_c
    command: python3 ./manage.py runserver 0.0.0.0:${DJANGO_PORT}
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
        - ./Backend:/app/backend
        - static_volume:/app/backend/staticfiles
        - media_volume:/app/backend/media
    env_file: ./.env

  frontend:
    image: frontend:latest
    build: ./Frontend
    container_name: frontend-latest_c
    command: npm start
    ports:
      - "${REACT_PORT}:${REACT_PORT}"
    volumes:
      - "./Frontend:/app/frontend"
    env_file: ./.env
    depends_on:
      - backend

volumes:
   postgres_data:
   static_volume:
   media_volume:
