# Generated by Django 4.1.6 on 2023-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cooking_difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cooking difficulty'),
        ),
    ]
